# Generated by Django 2.2 on 2020-07-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.CharField(default=1, max_length=25, verbose_name='data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('new', 'новая'), ('in_progress', 'В процессе'), ('done', 'Сделано')], default='new', max_length=25, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, max_length=25, verbose_name='Время изменения'),
        ),
    ]
