# Generated by Django 2.2 on 2020-08-06 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('task', 'задача'), ('Bug', 'ошибка'), ('Enhancement', 'улучшение.')], default='task', max_length=25, verbose_name='тип задачи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, max_length=25, verbose_name='Время создания'),
        ),
    ]
